insert into auto_category(name) values ('Chevrolet');
insert into auto_category(name) values ('Mers');
insert into auto_model(name ,count_seat,auto_category_id) values ('NEXIA' ,4,1);
insert into auto_model(name ,count_seat,auto_category_id) values ('Laceti' ,4,1);
insert into auto_model(name ,count_seat,auto_category_id) values ('Kaptiva' ,4,1);
insert into auto_model(name ,count_seat,auto_category_id) values ('Gelik' ,4,2);
insert into auto_model(name ,count_seat,auto_category_id) values ('G8' ,4,2);
insert into region ( name) values ('Toshkent');
insert into region ( name) values ('Samarqand');
insert into region ( name) values ('Namangan');
insert into region ( name) values ('Andijon');
insert into region ( name) values ('Farg`ona');
insert into region ( name) values ('Jizzax');
insert into city ( name ,region_id) values ('CHilonzor sh' ,1);
insert into city ( name ,region_id) values ('olmazor sh' ,1);
insert into city ( name ,region_id) values ('Yunusobod sh' ,1);
insert into city ( name ,region_id) values ('Samarqand sh' ,2);
insert into city ( name ,region_id) values ('Urgut sh' ,2);
insert into city ( name ,region_id) values ('Yakkobog sh' ,2);
insert into role (name) values ('ADMIN');
insert into role (name) values ('HAYDOVCHI');
insert into role (name) values ('YOLOVCHI');
